config/routes.rb
Rails.application.routes.draw do
  
  root 'nsmoking_area#index'
  
  get '/nsmoking_area/index' => 'nsmoking_area#index'
  
  get '/user_register/index' => 'user_register#index'

  post '/user_register/create' => 'user_register#create'

  get '/user_register/destroy' =>  'user_register#destroy'

  get '/qna/index' =>  'qna#index'

  get '/qna/new' =>  'qna#new'

  get '/qna/create' => 'qna#create'

  get '/qna/destroy' => 'qna#destroy'

  devise_for :user_registers
  resources :notices

  get '/place_register/index_smoke' => 'place_register#index_smoke'

  get '/place_register/new_smoke'    => 'place_register#new_smoke'

  post '/place_register/create_smoke' =>  'place_register#create_smoke'

  get '/place_register/index_penalty' => 'place_register#index_penalty'

  get '/place_register/index_create' =>  'place_register#index_create'

  get '/place_register/destroy' => 'place_register#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/nsmoking_area.rb
class NsmokingArea < ApplicationRecord
end

app/models/place_register.rb
class PlaceRegister < ApplicationRecord
end

app/models/qna.rb
class Qna < ApplicationRecord
end

app/models/user_register.rb
class UserRegister < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :string, :content, :text, :count, :integer)
    end
end

app/controllers/nsmoking_area_controller.rb
class NsmokingAreaController < ApplicationController
  before_action :set_smoking_area, only: [:show, :edit, :update, :destroy]

   require 'csv'  

  def index
    @nsmoking_areas = NsmokingArea.all
  end
  
  
  
  
  

  private
    def set_smoking_area
      @nsmoking_area = NsmokingArea.find(params[:id])
    end
  
    def smoking_area_params
      params.require(:nsmoking_area).permit(:area_name, :latitude, :longitude, :area_catagory, :statute, :penalty, :address)
    end
  
end

app/controllers/place_register_controller.rb
class PlaceRegisterController < ApplicationController
  
  # before_action :authenticate_user! , except: [:index, :show]
  # before_action :set_place_register, only: [:new_smoke, :create_smoke, :update, :destroy]
  
  def index_smoke
  end

  def new_smoke
    @place_register = PlaceRegister.new
  end

  def create_smoke
    @place_register = PlaceRegister.create(place_register_params)
  end

  def index_penalty
  end

  def index_create
  end

  def destroy
  end
  
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_register
      @place_register = PlaceRegister.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_register_params
      params.require(:place_register).permit(:area_type, :area_name, :description, :address, :latitude, :longitude, :image_path)
    end

end

app/controllers/qna_controller.rb
class QnaController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/user_register_controller.rb
class UserRegisterController < ApplicationController
  def index
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/nsmoking_area_helper.rb
module NsmokingAreaHelper
end

app/helpers/place_register_helper.rb
module PlaceRegisterHelper
end

app/helpers/qna_helper.rb
module QnaHelper
end

app/helpers/user_register_helper.rb
module UserRegisterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>흡연구역 알리미</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= stylesheet_link_tag   params[:controller], media: 'all' %>
    <!--# 컨트롤마다 css 파일 쓰는게 다르기 때문에 다르게 적용시켜줄 것임-->
    <!-- movie 컨르롤러는 movie.css 가 쓰이게끔 적용 가능 -->
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800,900" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    <!-- icon -->
    <link rel="icon" href="<%= asset_path 'log.png'%>">
    <!-- end linking -->
  </head>

  <body>
    <section id="admin">
      <%= render 'shared/sidebar' %>
      <div class="content">
        <%= render 'shared/top' %>
        <%= yield %>
      </div>
    </section>    
      <%= yield 'javascript_content' %>   <!-- 여기로 가라 -->
    
  </body>
</html>

app/views/notices/_form.html.erb
<%= form_for(notice) do |f| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :count %>
    <%= f.text_field :count %>
  </div>

  <div class="field">
    <%= f.label :integer %>
    <%= f.text_field :integer %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>String</th>
      <th>Content</th>
      <th>Text</th>
      <th>Count</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.string %></td>
        <td><%= notice.content %></td>
        <td><%= notice.text %></td>
        <td><%= notice.count %></td>
        <td><%= notice.integer %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>String:</strong>
  <%= @notice.string %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<p>
  <strong>Text:</strong>
  <%= @notice.text %>
</p>

<p>
  <strong>Count:</strong>
  <%= @notice.count %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @notice.integer %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>

app/views/nsmoking_area/index.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>흡연구역 알리미</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <!-- end head bottom -->
  </div>
<div class="container">
    <div id="map" style="width:100%;height:650px;"></div>
</div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=55748873ce3778b86bb7057ea1fd9548"></script>
<script>

var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new daum.maps.LatLng(37.4977796, 127.0755652), // 지도의 중심좌표
        level: 4 // 지도의 확대 레벨
    };  

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
if (navigator.geolocation) {
    
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {
        
        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도
        
        var locPosition = new daum.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<center><div style="padding:5px;">현재 위치!</div></center>'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
            
      });
    
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
    var locPosition = new daum.maps.LatLng(33.450701, 126.570667),    
        message = 'geolocation을 사용할수 없어요..'
        
    displayMarker(locPosition, message);
}


// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new daum.maps.Marker({  
        map: map, 
        position: locPosition
    }); 
    
    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new daum.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);      
}    


var latitude = []; 
var longitude = [];    // 위도 경도 자료 위치

var sw = [],          //   배열 생성
    ne = [];
    
var rectangleBounds = [];



daum.maps.event.addListener(map, 'zoom_changed', function() {        
    
    // 지도의 현재 레벨을 얻어옵니다
    var level = map.getLevel();
    console.log(level);
});


<% @nsmoking_areas.each do |smoking_area| %>
   
latitude = <%= smoking_area.latitude %>   // 한번씩 뽑아서 위도, 경도에 넣어줌.
longitude = <%= smoking_area.longitude %> 


// // 지도에 표시할 원을 생성합니다
// var circle = new daum.maps.Circle({
//     center : new daum.maps.LatLng(37.4977796, 127.0755652),  // 원의 중심좌표 입니다 
//     radius: 20, // 미터 단위의 원의 반지름입니다 
//     strokeWeight: 1, // 선의 두께입니다 
//     strokeColor: '#b30000', // 선의 색깔입니다
//     strokeOpacity: 0.7, // 선의 불투명도 입니다 1에서 0 사이의 값이며 0에 가까울수록 투명합니다
//     strokeStyle: 'solid', // 선의 스타일 입니다
//     fillColor: '#b30000', // 채우기 색깔입니다
//     fillOpacity: 0.7  // 채우기 불투명도 입니다   
// }); 

// // 지도에 원을 표시합니다 
// circle.setMap(map); 

sw = new daum.maps.LatLng(latitude + 0.0002, longitude + 0.0002), // 사각형 영역의 남서쪽 좌표
ne = new daum.maps.LatLng(latitude - 0.0002, longitude - 0.0002); // 사각형 영역의 북동쪽 좌표


// 사각형을 구성하는 영역정보를 생성합니다
// 사각형을 생성할 때 영역정보는 LatLngBounds 객체로 넘겨줘야 합니다
rectangleBounds = new daum.maps.LatLngBounds(sw, ne);


// 지도에 표시할 사각형을 생성합니다
var rectangle = new daum.maps.Rectangle({
    bounds: rectangleBounds, // 그려질 사각형의 영역정보입니다
    strokeWeight: 1, // 선의 두께입니다
    strokeColor: '#ff3333', // 선의 색깔입니다
    strokeOpacity: 0.7, // 선의 불투명도 입니다 1에서 0 사이의 값이며 0에 가까울수록 투명합니다
    strokeStyle: 'solid', // 선의 스타일입니다
    fillColor: '#ff3333', // 채우기 색깔입니다
    fillOpacity: 0.7 // 채우기 불투명도 입니다
});
// 지도에 사각형을 표시합니다
rectangle.setMap(map);
<% end %>

</script>


  <!-- panel script -->
  <% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  console.log("smoking_areas.index");
  </script>
  <% end %>
  

app/views/place_register/create_smoke.html.erb
<h1>PlaceRegister#create_smoke</h1>
<p>Find me in app/views/place_register/create_smoke.html.erb</p>

app/views/place_register/destroy.html.erb
<h1>PlaceRegister#destroy</h1>
<p>Find me in app/views/place_register/destroy.html.erb</p>

app/views/place_register/index_create.html.erb
<h1>PlaceRegister#index_create</h1>
<p>Find me in app/views/place_register/index_create.html.erb</p>

app/views/place_register/index_penalty.html.erb
<h1>PlaceRegister#index_penalty</h1>
<p>Find me in app/views/place_register/index_penalty.html.erb</p>

app/views/place_register/index_smoke.html.erb
<h1>PlaceRegister#index_smoke</h1>
<p>Find me in app/views/place_register/index_smoke.html.erb</p>

app/views/place_register/new_smoke.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>흡연구역 등록하기</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <!-- end head bottom -->
  </div>

<div id="map" style="width:100%;height:400px;"></div>               <!-- figaro 써서 정리해줄것! (환경변수로 추가함!)-->
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=55748873ce3778b86bb7057ea1fd9548"></script>

<%= form_for @place_register, url: {action: "create_smoke"} do |f| %>
 <p> 위도 : <%= f.text_field :latitude, id: 'lat' %>  </p>   <!-- //id 값에다가 넣을 것임! -->
 <p> 경도 : <%= f.text_field :longitude, id: 'lng' %>  </p>
 <p> 장소 종류 : <%= select_tag(:area_type, options_for_select([['흡연구역', 1], ['단속구역', 2]])) %></p>
 <p> 장 소 명 : <%= f.text_field :area_name %><br>  </p>
 <p> 장소 설명 : <%= f.text_area :description %></p> 
 <p> 사진등록 : <%= f.file_field :image_path, class: "form-control" %></p>
 <%= f.submit "등록하기" %>
<% end %>


<script>
    
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new daum.maps.LatLng(37.50130781924354, 127.03929932805282), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다


// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
if (navigator.geolocation) {
    
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {
        
        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도
        
        var locPosition = new daum.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<center><div style="padding:5px;">현재 위치!</div></center>'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
            
      });
    
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
    var locPosition = new daum.maps.LatLng(33.450701, 126.570667),    
        message = 'geolocation을 사용할수 없어요..'
        
    displayMarker(locPosition, message);
}


// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new daum.maps.Marker({  
        map: map, 
        position: locPosition
    }); 
    
    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new daum.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);      
}    

// 지도를 클릭한 위치에 표출할 마커입니다
var marker = new daum.maps.Marker({ 
    // 지도 중심좌표에 마커를 생성합니다 
    position: map.getCenter() 
}); 
// 지도에 마커를 표시합니다
marker.setMap(map);

// 지도에 클릭 이벤트를 등록합니다
// 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다

daum.maps.event.addListener(map, 'click', function(mouseEvent) {        
// 객체 안에 maps 안에 event               function 하나의 덩어리 
    // 클릭한 위도, 경도 정보를 가져옵니다 
    var latlng = mouseEvent.latLng;             // 값들의 덩어리 객체!
                                            // 필요한 것들만 뽑아서 써야함!
    // 마커 위치를 클릭한 위치로 옮깁니다
    marker.setPosition(latlng);
    
    var lat = latlng.getLat();    // html 태그 안에 값을 넣을 것임!
        lng = latlng.getLng();
    
    document.getElementById('lat').value = lat;
    document.getElementById('lng').value = lng;  
    console.log(lat);
    console.log(lng);
    
    console.log(typeof lat);
    
    // $('.lat').val('lat');
    
});

</script>

app/views/qna/create.html.erb
<h1>Qna#create</h1>
<p>Find me in app/views/qna/create.html.erb</p>

app/views/qna/destroy.html.erb
<h1>Qna#destroy</h1>
<p>Find me in app/views/qna/destroy.html.erb</p>

app/views/qna/index.html.erb
<h1>Qna#index</h1>
<p>Find me in app/views/qna/index.html.erb</p>

app/views/qna/new.html.erb
<h1>Qna#new</h1>
<p>Find me in app/views/qna/new.html.erb</p>

app/views/shared/_sidebar.html.erb
  <!-- start sidebar -->
  <div class="sidebar">
    <!-- start with head -->
    <div class="head">
      <div class="logo">
        <img src="<%= asset_path 'main-img.png' %>" alt="">
      </div>
      <a href="/" class="btn btn-danger">Smoking Map</a>
    </div>
    <!-- end with head -->
    <!-- start the list -->
    <div id="list">
      <ul class="nav flex-column">
        <li class="nav-item"><a href="/nsmoking_area/index" class="nav-link active" ><i class="fa fa-map" aria-hidden="true"></i>지도보기</a></li>
        <li class="nav-item"><a href="/place_register/new_smoke" class="nav-link active" ><i class="fa fa-registered" aria-hidden="true"></i>흡연구역 등록</a></li>
        <li class="nav-item"><a href="/place_register/index_smoke" class="nav-link active" ><i class="fa fa-list-ul" aria-hidden="true"></i>  흡연구역 목록</a></li>
        <li class="nav-item"><a href="/index.html" class="nav-link active" ><i class="fa fa-registered" aria-hidden="true"></i>단속구역 등록</a></li>
        <li class="nav-item"><a href="/index.html" class="nav-link active" ><i class="fa fa-list-ul" aria-hidden="true"></i>  단속구역 목록</a></li>
        <li class="nav-item"><a href="/qna/new" class="nav-link active" ><i class="fa fa-circle" aria-hidden="true"></i>문의사항</a></li>
        <li class="nav-item"><a href="/notices" class="nav-link active" ><i class="fa fa-circle" aria-hidden="true"></i>공지사항</a></li>

        <!-- end user interface submenu -->
        <!-- start with charts -->
      <!--  <li class="nav-item"><a href="#menu3" class="nav-link collapsed" data-toggle="collapse"><i class="fa fa-fire"></i>ui<span class="sub-ico"><i class="fa fa-angle-down"></i></span></a></li>-->
        <!-- start charts submenue -->
      <!--  <li class="sub collapse" id="menu3">-->
      <!--      <a href="ui-alerts.html" class="nav-link" data-parent="#menu3">alerts</a>-->
      <!--      <a href="ui-btns.html" class="nav-link" data-parent="#menu3">buttons</a>-->
      <!--      <a href="ui-cards.html" class="nav-link" data-parent="#menu3">cards</a>-->
      <!--      <a href="ui-list.html" class="nav-link" data-parent="#menu3">list</a>-->
      <!--      <a href="ui-progress-bars.html" class="nav-link" data-parent="#menu3">progress</a>-->
      <!--  </li>-->
        <!-- end charts submenue -->
        <!-- end with charts -->
      <!--  <li class="nav-item"><a href="inbox.html" class="nav-link"><i class="fa fa-inbox"></i>inbox</a></li>-->
      <!--  <li class="nav-item"><a href="contacts.html" class="nav-link"><i class="fa fa-user"></i>contact</a></li>-->
      <!--  <li class="nav-item"><a href="forms.html" class="nav-link"><i class="fa fa-edit"></i>forms</a></li>-->
      <!--  <li class="nav-item"><a href="tabels.html" class="nav-link"><i class="fa fa-table"></i>tables</a></li>-->
      <!--  <li class="nav-item"><a href="profile.html" class="nav-link"><i class="fa fa-users"></i>profile</a></li>-->
      <!--  <li class="nav-item"><a href="invoice.html" class="nav-link"><i class="fa fa-money-bill-alt"></i>invoice</a></li>-->
      <!--  <li class="nav-item"><a href="price.html" class="nav-link"><i class="fa fa-dollar-sign"></i>price</a></li>-->
      <!--  <li class="nav-item"><a href="support.html" class="nav-link"><i class="fa fa-life-ring"></i>support</a></li>-->
      <!--</ul>-->
    </div>
    <!-- end the list -->
  </div>
  <!-- end sidebar -->

app/views/shared/_top.html.erb
  <!-- start content head -->
  <div class="head">
    <!-- head top -->
    <div class="top">
      <div class="left">
        <button id="off" class="btn btn-info hide"><i class="fa fa-align-left"></i></button>
        <button id="on" class="btn btn-info"><i class="fa fa-bars"></i></button>
        <!--<button class="btn btn-info hidden-xs-down"><i class="fa fa-expand-arrows-alt"></i></button>-->
        <button class="btn btn-info hidden-xs-down" onClick="location.href='/'"><i class="fa fa-home"></i>Back Home</button>
      </div>
      <div class="right">
        <button class="btn btn-primary hidden-xs-down">흡연구역 등록하기</button>
        <button class="btn btn-primary hidden-xs-down">단속구역 등록하기</button>
        <button class="btn btn-success hidden-xs-down"><i class="fa fa-envelope "></i>문의사항</button></button>
        <!--<button class="btn btn-info hidden-xs-down"><i class="fa fa-bell"></i></button>-->
        <!--<button class="btn btn-info hidden-xs-down"><i class="fa fa-envelope"></i></button>-->

        <div class="dropdown">
                <!--<@% if # 로그인이 되어있다면 아래 2개가 뜨게끔 처리하기 %>-->
          <button class="btn btn-info dropdown-toggle" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ㅋㅋㅋ</button>
            <div class="dropdown-menu" aria-labelledby="userDropdown">
           <!--<a class="dropdown-item" href="#">내 계정</a>-->
           <!--<a class="dropdown-item" href="#">Log out</a>-->
           
                <!--<@% if # 로그인이 되어있지 않다면 %>-->
                           <!--<a class="dropdown-item" href="#">Log out</a>-->
         </div>
        </div>
      </div>
    </div>
    <!-- end head top -->

app/views/user_register/create.html.erb
<h1>UserRegister#create</h1>
<p>Find me in app/views/user_register/create.html.erb</p>

app/views/user_register/destroy.html.erb
<h1>UserRegister#destroy</h1>
<p>Find me in app/views/user_register/destroy.html.erb</p>

app/views/user_register/index.html.erb
<h1>UserRegister#index</h1>
<p>Find me in app/views/user_register/index.html.erb</p>